#Change to FROM the arm compatible docker-headless-vnc-container build
FROM consol/ubuntu-xfce-vnc:1.3.0

USER 0

RUN apt-get -y update && apt-get -y install curl && apt-get -y install chef && apt-get -y update && apt-get -y install default-jre

